### ISSUE TITLE
Error occured only on Windows

### ISSUE THREAD

**Issue by sti1l-0** [KristoforMaynard/music-tag#24]
Error occured when adding an artwork to a m4a file on Windows, however, it's success on macOS and Linux.

failed on my project on windows
![image](https://user-images.githubusercontent.com/37724877/144019353-77008086-953a-4fd3-87d1-49e398d690a7.png)
test with code
```python
import music_tag
a = music_tag.load_file(r'E:\Users\Documents\GitHub\ASoulMP3maker\a.m4a')
a['artwork'] = open(r'E:\Users\Documents\GitHub\ASoulMP3maker\j.jpg','rb').read()
a.save()
```
error info on window
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\17374\AppData\Local\Programs\Python\Python39\lib\site-packages\music_tag\file.py", line 603, in __setitem__
    self.set(norm_key, val)
  File "C:\Users\17374\AppData\Local\Programs\Python\Python39\lib\site-packages\music_tag\file.py", line 503, in set
    tmap.setter(self, norm_key, val)
  File "C:\Users\17374\AppData\Local\Programs\Python\Python39\lib\site-packages\music_tag\mp4.py", line 99, in set_artwork
    raise TypeError('mp4 artwork should be either jpeg or png')
TypeError: mp4 artwork should be either jpeg or png
```
success on linux
![image](https://user-images.githubusercontent.com/37724877/144021270-1b3226dc-4136-4618-9698-d24154c20227.png)

Here is the m4a file i wanna edit.

[musicfile.zip](https://github.com/KristoforMaynard/music-tag/files/7624486/musicfile.zip)

**Comment by sti1l-0** [comment]
fixed when i try pip install pillow.
Maybe you should add PIL into your setup.py/install_requires
